assert = chai.assert;

describe('Testing function', function () {

    it('Test 1: Check if passowrd is less than 8 characters', () => {
        for (var j = 1; j < 1000; j++) {
            assert.equal(checkPassword(Math.random().toString(36).slice(2, 10)), true);
        }
    });

    // it("Test 2: Check if it's a valid email", () => {
    //     for (var m = 1; m < 1000; m++) {
    //         email=makeEmail()
    //         assert.equal(isValidEmail(email),);
    //     }
    // });
//     it("Test 3: Check if password and confirm password match(In this case it shouldn't because the password are generated by random module)", () => {
//         for (var m = 1; m < 10; m++) {
//             pass1=Math.random().toString(36).slice(2, 10);
//             pass2=Math.random().toString(36).slice(2, 10)
//             assert.equal(matchPasswords(pass1,pass2),`passwords must match`);
//         }
//     });

});
// function makeEmail() {
//     var strValues = "abcdefg12345";
//     var strEmail = "";
//     var strTmp;
//     for (var i = 0; i < 10; i++) {
//         strTmp = strValues.charAt(Math.round(strValues.length * Math.random()));
//         strEmail = strEmail + strTmp;
//     }
//     strTmp = "";
//     strEmail = strEmail + "@";
//     for (var j = 0; j < 8; j++) {
//         strTmp = strValues.charAt(Math.round(strValues.length * Math.random()));
//         strEmail = strEmail + strTmp;
//     }
//     strEmail = strEmail + ".com"
//     return strEmail;
// }